plugins {
    id 'org.springframework.boot' version '3.4.1'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'groovy'
    id 'java-library'
    id 'maven-publish'
    id 'com.github.ben-manes.versions' version '0.53.0'
    id 'se.patrikerdes.use-latest-versions' version '0.2.18'
}

group = 'no.novari'
version = System.getenv("RELEASE_VERSION") ?: '0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    maven {
        url 'https://repo.fintlabs.no/releases'
    }
    mavenLocal()
    mavenCentral()
}

dependencies {
    implementation 'no.novari:fint-model-resource:1.0.0-rc-3'
    implementation "no.fint:fint-relation-model:2.0.0-rc.1"

    implementation 'org.springframework.hateoas:spring-hateoas'
    implementation 'jakarta.annotation:jakarta.annotation-api'
    implementation 'com.fasterxml.jackson.core:jackson-databind'

    implementation 'org.apache.commons:commons-text:1.13.0'
    implementation 'com.google.guava:guava:33.5.0-jre'

    compileOnly 'org.projectlombok:lombok:1.18.36'
    annotationProcessor 'org.projectlombok:lombok:1.18.36'
    testCompileOnly 'org.projectlombok:lombok:1.18.36'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.36'

    testImplementation 'org.springframework.boot:spring-boot-starter-web'
    testImplementation 'org.springframework.boot:spring-boot-starter-aop'

    testImplementation 'cglib:cglib-nodep:3.3.0'

    testImplementation 'org.spockframework:spock-spring:2.4-groovy-3.0'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

bootJar {
    enabled = false
}

jar {
    enabled = true
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

test {
    useJUnitPlatform()
}

publishing {
    repositories {
        maven {
            url "https://repo.fintlabs.no/releases"
            credentials {
                username = System.getenv("REPOSILITE_USERNAME")
                password = System.getenv("REPOSILITE_PASSWORD")
            }
            authentication {
                basic(BasicAuthentication)
            }
        }
    }
    publications {
        maven(MavenPublication) {
            from(components.java)
        }
    }
}